[phases.setup]
nixPkgs = ["python311", "tesseract", "poppler_utils"]

[phases.install]
cmds = [
  "/opt/venv/bin/pip install -r requirements.txt",
  "/opt/venv/bin/python -m spacy download en_core_web_lg"
]

[start]
cmd = "uvicorn api.main:app --host 0.0.0.0 --port $PORT"
